### ISSUE TITLE
I did not find which version is this implementation

### ISSUE THREAD

**Issue by phtdacosta** [tecnickcom/farmhash64#2]
According to the official farmhash repository, the latest update is the 1.1 but I did not find if this one strictly follows the latter, it would be good to put this straight into the README.

Although, I really like to thank you for the amazing effort to implement this hash into plain C. I was looking for some hash functions for a new project and was a bit sad that a really nice algorithm like farmhash was not directly suitable for plain C use.
I will look forward to try out your code and for sure will come back to give any feedback about it.

One last question, if you can say, are yourself using this implementation for which kind of projects? Is this repository planned to be active overtime?

_Keep it up that nice job!_

**Comment by nicolaasuni** [comment]
Yes, this version is derived from the 1.1 google version:
https://github.com/google/farmhash/tree/2f0e005b81e296fa6963e395626137cf729b710c
I have only focused on the 64 bit hash version and provided an additional non standard 32 bit version derived from the 64.
I have also add tests to cover 100% of statements and be confident that the binding and implementations in other languages are consistent.
